"""Deleted BaseModelMixin

Revision ID: 48b7145fb225
Revises: df2ea3f78dcc
Create Date: 2025-07-10 14:04:34.378392

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48b7145fb225"
down_revision: Union[str, Sequence[str], None] = "df2ea3f78dcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
