services:
  web:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
    command: sh -c "uvicorn app.main:app --host localhost --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - redis
    env_file:
      - ../.env
    volumes:
      - ../:/app

  celery:
    build:
      context: ..
      dockerfile: config/docker/Dockerfile
    command: celery -A boycott_platform worker -l info
    depends_on:
      - redis
      - postgres_db
    env_file:
      - ../.env
    volumes:
      - ../:/app

  postgres_db:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  boycott_network:
    driver: bridge
